---
- hosts: all
  ansible_become: true
  roles:
    - common
    - kubernetes
    - { role: kubevirt, ansible_become: false }
    - { role: local-storage, ansible_become: false }
    - { role: helm, ansible_become: false }
    - { role: prometheus, ansible_become: false }
