---
- name: Add nf-call-iptables sysctl knob
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present
    reload: yes

- name: Enable and start kubelet
  systemd:
    state: started
    enabled: yes
    name: kubelet

- name: Partition disks for local storage
  parted:
    device: "/dev/{{ item }}"
    number: 1
    state: present
  loop:
    - vdb
    - vdc
    - vdd
    - vdf
    - vde

- name: Format disks for local storage
  filesystem:
    dev: /dev/{{ item }}1
    fstype: xfs
    opts: -L {{ item }}
  loop:
    - vdb
    - vdc
    - vdd
    - vdf
    - vde

- name: Create base directory for local storage
  file:
    state: directory
    path: /mnt/storage

- name: Mount disks for local storage
  mount:
    path: /mnt/storage/{{ item }}
    src: LABEL={{ item }}
    fstype: xfs
    state: mounted
  loop:
    - vdb
    - vdc
    - vdd
    - vdf
    - vde

- name: Create facts directory
  file:
    state: directory
    path: /etc/ansible/facts.d
