---
- name: '[Libvirt] Partition disks for local storage'
  parted:
    device: "/dev/{{ item }}"
    number: 1
    state: present
  loop: "{{ libvirt_devices }}"

- name: '[Libvirt] Format disks for local storage'
  filesystem:
    dev: /dev/{{ item }}1
    fstype: xfs
    opts: -L {{ item }}
  loop: "{{ libvirt_devices }}"

- name: '[Libvirt] Mount disks for local storage'
  mount:
    path: /mnt/storage/{{ item }}
    src: LABEL={{ item }}
    fstype: xfs
    state: mounted
  loop: "{{ libvirt_devices }}"
