---
- name: Create Prometheus namespace
  k8s:
    state: present
    name: prometheus
    kind: Namespace
    api_version: v1

- name: Get an existing Service object
  k8s_facts:
    api_version: v1
    kind: Deployment
    name: kubevirtlab-prometheus-ope-operator
    namespace: default
  register: promop_deployment

- name: Install Prometheus
  command: ~/.local/bin/helm install --name kubevirtlab --wait --set grafana.adminPassword=kubevirtlab123 --set prometheus.service.type=NodePort --namespace prometheus stable/prometheus-operator
  when: not (promop_deployment['resources'] | length > 0)

- name: Expose grafana on a nodeport
  k8s:
    name: kubevirtlab-grafana-nodeport
    namespace: prometheus
    kind: Service
    api_version: v1
    resource_definition:
      spec:
        selector:
          app: grafana
        ports:
        - protocol: TCP
          port: 3000
          nodePort: 30300
        type: NodePort
