---
kind: ConfigMap
apiVersion: v1
metadata:
  name: multus-cni-config
  namespace: multus
  labels:
    tier: node
    app: multus
data:
  00-multus.conf: |
    {
      "name": "multus-cni-network",
      "type": "multus",
      "delegates": [
       {
         "type": "flannel",
         "name": "flannel.1",
         "delegate": {
           "isDefaultGateway": true
         }
       }
      ],
      "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
    }